# gh search commits --hash 272effd --repo dgatf/msrc

name: CI - MSRC firmware

on:
  workflow_dispatch:
  schedule:
      - cron: '0 0 1 * *'
  push:
    branches:
      - master
    paths:
      - board/**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        id-token: write 
        attestations: write

    steps:
      - name: Get actions code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Git tags
        run: git fetch --prune --unshallow

      - name: Build firmware
        uses: samyarsadat/Pico-Build-Action@v1
        with:
          source_dir: "board"
          output_dir: "../build"
          cmake_args: "-DCMAKE_BUILD_TYPE=Release"
        
      - name: Generate attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: build/project/MSRC-RP2040.uf2
          github-token: ${{ secrets.TOKEN }}

      #- name: Upload artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    overwrite: 'true'
      #    name: MSRC-RP2040.uf2
      #    path: build/project/MSRC-RP2040.uf2]]

      - name: Upload to Google Drive
        uses: logickoder/g-drive-upload@main
        with:
          credentials: ${{ secrets.GOOGLE_ID }}
          filename: 'build/project/MSRC-RP2040.uf2'
          folderId: ${{ secrets.FOLDER_ID }}
          overwrite: 'true'
          name: MSRC-RP2040.uf2
