name: CI - MSRC Link

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - msrc_gui/**

jobs:
  linux:
    runs-on: ubuntu-22.04
    permissions:
        contents: read
        id-token: write 
        attestations: write

    steps:
      - name: Get actions code
        uses: actions/checkout@v4
        
      - name: Install QT
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.*'
          modules: qtserialport

      - name: Git tags
        run: git fetch --prune --unshallow

      - name: Build
        run: |
          mkdir build
          cd build
          qmake ../msrc_gui
          make
          
      - name: Install LinuxDeploy
        run: |
          cd msrc_gui
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          sudo chmod +x linuxdeployqt-continuous-x86_64.AppImage
      
      - name: Install fuse
        run: sudo apt install libfuse2

      - name: Create AppImage
        run: |
          cp build/msrc_gui msrc_gui/appdir
          cd msrc_gui/appdir
          ../linuxdeployqt-continuous-x86_64.AppImage msrc.desktop -appimage -extra-plugins=iconengines,platformthemes/libqgtk3.so
          mv *.AppImage msrc_gui.AppImage

      - name: Generate attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: msrc_gui/appdir/msrc_gui.AppImage
          github-token: ${{ secrets.TOKEN }}

      - name: Upload to Google Drive
        uses: logickoder/g-drive-upload@main
        with:
          credentials: ${{ secrets.GOOGLE_ID }}
          filename: 'msrc_gui/appdir/msrc_gui.AppImage'
          folderId: ${{ secrets.FOLDER_ID }}
          overwrite: 'true'
          name: msrc_link.AppImage

  macos:
    runs-on: macos-14
    permissions:
        contents: read
        id-token: write 
        attestations: write

    steps:
      - name: Get actions code
        uses: actions/checkout@v4
        
      - name: Install QT
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.*'
          modules: qtserialport
        
      - name: Git tags
        run: git fetch --prune --unshallow
      
      - name: Build
        run: |
          mkdir build
          cd build
          qmake ../msrc_gui
          make
          macdeployqt msrc_gui.app -dmg

      - name: Generate attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: build/msrc_gui.dmg
          github-token: ${{ secrets.TOKEN }}
        
      - name: Upload to Google Drive
        uses: logickoder/g-drive-upload@main
        with:
          credentials: ${{ secrets.GOOGLE_ID }}
          filename: 'build/msrc_gui.dmg'
          folderId: ${{ secrets.FOLDER_ID }}
          overwrite: 'true'
          name: msrc_link.dmg

  windows:
    runs-on: windows-2022
    permissions:
        contents: read
        id-token: write 
        attestations: write

    steps:
      - name: Get actions code
        uses: actions/checkout@v4
        
      - name: install qt static
        uses: orestonce/install-qt-static@v0.4.3
        with:
          version: Qt6.5.3-Windows-x86_64-MinGW13.2.0-ucrt-staticFull-20240527

      - name: Git tags
        run: git fetch --prune --unshallow
        
      - name: Build  
        run: |
          mkdir build
          cd build
          qmake ../msrc_gui
          make
          mingw32-make release

      - name: Generate attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: build/release/msrc_gui.exe
          github-token: ${{ secrets.TOKEN }}

      - name: Upload to Google Drive
        uses: logickoder/g-drive-upload@main
        with:
          credentials: ${{ secrets.GOOGLE_ID }}
          filename: 'build/release/msrc_gui.exe'
          folderId: ${{ secrets.FOLDER_ID }}
          overwrite: 'true'
          name: msrc_link.exe